/* eslint-disable no-unused-vars */
export enum ACTIVE_STATUS_ENUM {
  ACTIVE = "ACTIVE",
  BLACKLISTED = "BLACKLISTED",
  DISABLED = "DISABLED",
  EXPIRED = "EXPIRED",
  IN_ACTIVE = "IN_ACTIVE",
}

export enum EMPLOYEE_ROLE_ENUM {
  ADMIN = "ADMIN",
  CUSTOMER_SUPPORT = "CUSTOMER_SUPPORT",
  MANAGER = "MANAGER",
}

export enum USER_ROLE_ENUM {
  USER = "USER",
}

export enum CONTACT_METHOD {
  MOBILE = "MOBILE",
  SMS = "SMS",
  EMAIL = "EMAIL",
}

export enum SHIPMENT_STATUS {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  SHIPPED = "SHIPPED",
  IN_TRANSIT = "IN_TRANSIT",
  OUT_DELIVERY = "OUT_DELIVERY",
  DELIVERED = "DELIVERED",
  FAILED = "FAILED",
}

export enum PAYMENT_STATUS {
  PENDING = "PENDING",
  PAID = "PAID",
  FAILED = "FAILED",
  REFUNDED = "REFUNDED",
}

export enum ORDER_STATUS {
  PENDING = "PENDING",
  PROCESSING = "PROCESSING",
  SHIPPED = "SHIPPED",
  COMPLETED = "COMPLETED",
  CANCELED = "CANCELED",
}

export enum PAYMENT_METHOD {
  CREDIT = "CREDIT",
  DEBIT = "DEBIT",
  PAYPAL = "PAYPAL",
  BANK_TRANSFER = "BANK_TRANSFER",
  CASH = "CASH",
  MOBLE_TRANSFER = "MOBILE_TRANSFER",
}

export enum DISCOUNT_TYPE {
  PERCENTAGE = "PERCENTAGE",
  FLAT = "FLAT",
  FREE_SHIPPING = "FREE_SHIPPING",
}

export enum SUPPORTED_CURRENCY {
  USD = "USD",
  NPR = "NPR",
}

export enum BUSINESS_TYPE_ENUM {
  E_COMMERCE = "E_COMMERCE",
  RETAIL = "RETAIL",
  LOGISTICS = "LOGISTICS",
  OTHER = "OTHER",
}
