name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js with pnpm
      - name: Set up Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: "pnpm" # Cache dependencies for faster builds

      # Install pnpm
      - name: Install pnpm
        run: |
          npm install -g pnpm

      # Install dependencies in the monorepo
      - name: Install dependencies
        run: |
          pnpm install

      # Build the library package
      - name: Build library package
        working-directory: libs/react # Adjust to your library's directory
        run: |
          pnpm run build

      # Build the portfolio app
      - name: Build portfolio
        working-directory: apps/portfolio # Adjust to your portfolio's directory
        run: |
          pnpm run build
        env:
          VITE_APP_NAME: ${{ vars.VITE_APP_NAME }}
          VITE_APP_TITLE: ${{ vars.VITE_APP_TITLE }}
          VITE_APP_DESCRIPTION: ${{ vars.VITE_APP_DESCRIPTION }}
          VITE_APP_KEYWORDS: ${{ vars.VITE_APP_KEYWORDS }}
          VITE_APP_AUTHOR: ${{ vars.VITE_APP_AUTHOR }}
          VITE_COPYRIGHT_HOLDER: ${{ vars.VITE_COPYRIGHT_HOLDER }}

          VITE_BASE_APP_URL: ${{ vars.VITE_BASE_APP_URL }}

          VITE_APP_LINKEDIN_URL: ${{ vars.VITE_APP_LINKEDIN_URL }}
          VITE_APP_GITHUB_URL: ${{ vars.VITE_APP_GITHUB_URL }}
          VITE_APP_TWITTER_URL: ${{ vars.VITE_APP_TWITTER_URL }}
          VITE_APP_FACEBOOK_URL: ${{ vars.VITE_APP_FACEBOOK_URL }}
          VITE_APP_INSTAGRAM_URL: ${{ vars.VITE_APP_INSTAGRAM_URL }}
          VITE_APP_YOUTUBE_URL: ${{ vars.VITE_APP_YOUTUBE_URL }}

          VITE_APP_TWITTER_HANDLE: ${{ vars.VITE_APP_TWITTER_HANDLE }}

          VITE_APP_THEME_COLOR: ${{ vars.VITE_APP_THEME_COLOR }}
          VITE_APP_THEME_MULTI_COLOR_MODE: ${{ vars.VITE_APP_THEME_MULTI_COLOR_MODE }}

          VITE_APP_EMAIL: ${{ secrets.VITE_APP_EMAIL }}
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
          VITE_EMAILJS_USER_ID: ${{ secrets.VITE_EMAILJS_USER_ID }}

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PIT_TOKEN }}
          publish_dir: apps/portfolio/dist # Adjust to your portfolio's build output
